# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T01:09:49+00:00

from __future__ import annotations

from enum import Enum
from typing import List, Optional

from pydantic import BaseModel, Field


class DestinationRegion(Enum):
    CACHE_FILL_DESTINATION_REGION_UNSPECIFIED = (
        'CACHE_FILL_DESTINATION_REGION_UNSPECIFIED'
    )
    CACHE_FILL_DESTINATION_REGION_ASIA_PACIFIC = (
        'CACHE_FILL_DESTINATION_REGION_ASIA_PACIFIC'
    )
    CACHE_FILL_DESTINATION_REGION_EUROPE = 'CACHE_FILL_DESTINATION_REGION_EUROPE'
    CACHE_FILL_DESTINATION_REGION_NORTH_AMERICA = (
        'CACHE_FILL_DESTINATION_REGION_NORTH_AMERICA'
    )
    CACHE_FILL_DESTINATION_REGION_OCEANIA = 'CACHE_FILL_DESTINATION_REGION_OCEANIA'
    CACHE_FILL_DESTINATION_REGION_SOUTH_AMERICA = (
        'CACHE_FILL_DESTINATION_REGION_SOUTH_AMERICA'
    )
    CACHE_FILL_DESTINATION_REGION_CHINA = 'CACHE_FILL_DESTINATION_REGION_CHINA'
    CACHE_FILL_DESTINATION_REGION_OTHERS = 'CACHE_FILL_DESTINATION_REGION_OTHERS'


class SourceRegion(Enum):
    CACHE_FILL_SOURCE_REGION_UNSPECIFIED = 'CACHE_FILL_SOURCE_REGION_UNSPECIFIED'
    CACHE_FILL_REGION_ASIA_PACIFIC = 'CACHE_FILL_REGION_ASIA_PACIFIC'
    CACHE_FILL_SOURCE_REGION_EUROPE = 'CACHE_FILL_SOURCE_REGION_EUROPE'
    CACHE_FILL_SOURCE_REGION_NORTH_AMERICA = 'CACHE_FILL_SOURCE_REGION_NORTH_AMERICA'
    CACHE_FILL_SOURCE_REGION_OCEANIA = 'CACHE_FILL_SOURCE_REGION_OCEANIA'
    CACHE_FILL_SOURCE_REGION_SOUTH_AMERICA = 'CACHE_FILL_SOURCE_REGION_SOUTH_AMERICA'


class CacheFillRegions(BaseModel):
    destinationRegion: Optional[DestinationRegion] = Field(
        None, description='The destination region for cache fill.'
    )
    sourceRegion: Optional[SourceRegion] = Field(
        None, description='The source region for cache fill.'
    )


class CacheEgressDestination(Enum):
    CACHE_EGRESS_DESTINATION_UNSPECIFIED = 'CACHE_EGRESS_DESTINATION_UNSPECIFIED'
    CACHE_EGRESS_DESTINATION_ASIA_PACIFIC = 'CACHE_EGRESS_DESTINATION_ASIA_PACIFIC'
    CACHE_EGRESS_DESTINATION_CHINA = 'CACHE_EGRESS_DESTINATION_CHINA'
    CACHE_EGRESS_DESTINATION_EUROPE = 'CACHE_EGRESS_DESTINATION_EUROPE'
    CACHE_EGRESS_DESTINATION_NORTH_AMERICA = 'CACHE_EGRESS_DESTINATION_NORTH_AMERICA'
    CACHE_EGRESS_DESTINATION_OCEANIA = 'CACHE_EGRESS_DESTINATION_OCEANIA'
    CACHE_EGRESS_DESTINATION_LATIN_AMERICA = 'CACHE_EGRESS_DESTINATION_LATIN_AMERICA'
    CACHE_EGRESS_DESTINATION_OTHER_DESTINATIONS = (
        'CACHE_EGRESS_DESTINATION_OTHER_DESTINATIONS'
    )


class CacheFillOriginService(Enum):
    CACHE_FILL_ORIGIN_SERVICE_UNSPECIFIED = 'CACHE_FILL_ORIGIN_SERVICE_UNSPECIFIED'
    CACHE_FILL_ORIGIN_SERVICE_GOOGLE_CLOUD_STORAGE_BUCKET = (
        'CACHE_FILL_ORIGIN_SERVICE_GOOGLE_CLOUD_STORAGE_BUCKET'
    )
    CACHE_FILL_ORIGIN_SERVICE_BACKEND_SERVICE = (
        'CACHE_FILL_ORIGIN_SERVICE_BACKEND_SERVICE'
    )


class InterconnectConnectionLocation(Enum):
    INTERCONNECT_CONNECTION_LOCATION_UNSPECIFIED = (
        'INTERCONNECT_CONNECTION_LOCATION_UNSPECIFIED'
    )
    INTERCONNECT_CONNECTION_LOCATION_ASIA = 'INTERCONNECT_CONNECTION_LOCATION_ASIA'
    INTERCONNECT_CONNECTION_LOCATION_EUROPE = 'INTERCONNECT_CONNECTION_LOCATION_EUROPE'
    INTERCONNECT_CONNECTION_LOCATION_NORTH_AMERICA = (
        'INTERCONNECT_CONNECTION_LOCATION_NORTH_AMERICA'
    )
    INTERCONNECT_CONNECTION_LOCATION_SOUTH_AMERICA = (
        'INTERCONNECT_CONNECTION_LOCATION_SOUTH_AMERICA'
    )
    INTERCONNECT_CONNECTION_LOCATION_AUSTRALIA = (
        'INTERCONNECT_CONNECTION_LOCATION_AUSTRALIA'
    )


class InterconnectType(Enum):
    INTERCONNECT_TYPE_UNSPECIFIED = 'INTERCONNECT_TYPE_UNSPECIFIED'
    INTERCONNECT_TYPE_DEDICATED = 'INTERCONNECT_TYPE_DEDICATED'
    INTERCONNECT_TYPE_PARTNER = 'INTERCONNECT_TYPE_PARTNER'


class LinkType(Enum):
    LINK_TYPE_UNSPECIFIED = 'LINK_TYPE_UNSPECIFIED'
    LINK_TYPE_ETHERNET_10G_LR = 'LINK_TYPE_ETHERNET_10G_LR'
    LINK_TYPE_ETHERNET_100G_LR = 'LINK_TYPE_ETHERNET_100G_LR'


class DestinationContinent(Enum):
    DESTINATION_CONTINENT_UNSPECIFIED = 'DESTINATION_CONTINENT_UNSPECIFIED'
    DESTINATION_CONTINENT_ASIA_PACIFIC = 'DESTINATION_CONTINENT_ASIA_PACIFIC'
    DESTINATION_CONTINENT_AUTRALIA = 'DESTINATION_CONTINENT_AUTRALIA'
    DESTINATION_CONTINENT_EUROPE = 'DESTINATION_CONTINENT_EUROPE'
    DESTINATION_CONTINENT_NORTH_AMERICA = 'DESTINATION_CONTINENT_NORTH_AMERICA'
    DESTINATION_CONTINENT_SOUTH_AMERICA = 'DESTINATION_CONTINENT_SOUTH_AMERICA'


class SourceContinent(Enum):
    SOURCE_CONTINENT_UNSPECIFIED = 'SOURCE_CONTINENT_UNSPECIFIED'
    SOURCE_CONTINENT_ASIA_PACIFIC = 'SOURCE_CONTINENT_ASIA_PACIFIC'
    SOURCE_CONTINENT_AUSTRALIA = 'SOURCE_CONTINENT_AUSTRALIA'
    SOURCE_CONTINENT_EUROPE = 'SOURCE_CONTINENT_EUROPE'
    SOURCE_CONTINENT_NORTH_AMERICA = 'SOURCE_CONTINENT_NORTH_AMERICA'
    SOURCE_CONTINENT_SOUTH_AMERICA = 'SOURCE_CONTINENT_SOUTH_AMERICA'


class CustomMachineType(BaseModel):
    machineSeries: Optional[str] = Field(
        None,
        description='Required. The machine series. Only certain [machine series](https://cloud.google.com/compute/docs/general-purpose-machines#custom_machine_types) support custom configurations. For example: "n1".',
    )
    memorySizeGb: Optional[float] = Field(
        None,
        description='Required. Memory size of the VM in GB (2^30 bytes). Must be an increment of 0.25 (256 MB). Each [machine series](https://cloud.google.com/compute/docs/machine-types#machine_type_comparison) has limitations on allowed values for the ratio of memory-to-vCPU count.',
    )
    virtualCpuCount: Optional[str] = Field(
        None,
        description='Required. The number of vCPUs. The allowed values depend on the [machine series](https://cloud.google.com/compute/docs/machine-types#machine_type_comparison).',
    )


class DualRegional(BaseModel):
    name: Optional[str] = Field(
        None,
        description='The [location name](https://cloud.google.com/storage/docs/locations#available-locations) where the data is stored. For example: "asia1" for dual region.',
    )


class EstimationTimePoint(BaseModel):
    estimationTimeFrameOffset: Optional[str] = Field(
        None,
        description='The point in time, relative to the start of the time frame covered by the cost estimate.',
    )


class GuestAccelerator(BaseModel):
    acceleratorCount: Optional[str] = Field(
        None,
        description='The number of the guest accelerator cards exposed to each instance.',
    )
    acceleratorType: Optional[str] = Field(
        None,
        description='The type of the guest accelerator cards. For example: "nvidia-tesla-t4".',
    )


class Money(BaseModel):
    currencyCode: Optional[str] = Field(
        None, description='The three-letter currency code defined in ISO 4217.'
    )
    nanos: Optional[int] = Field(
        None,
        description='Number of nano (10^-9) units of the amount. The value must be between -999,999,999 and +999,999,999 inclusive. If `units` is positive, `nanos` must be positive or zero. If `units` is zero, `nanos` can be positive, zero, or negative. If `units` is negative, `nanos` must be negative or zero. For example $-1.75 is represented as `units`=-1 and `nanos`=-750,000,000.',
    )
    units: Optional[str] = Field(
        None,
        description='The whole units of the amount. For example if `currencyCode` is `"USD"`, then 1 unit is one US dollar.',
    )


class MultiRegional(BaseModel):
    name: Optional[str] = Field(
        None,
        description='The [location name](https://cloud.google.com/storage/docs/locations#available-locations) where the data is stored. For example: "us" for multi-region.',
    )


class Scope(Enum):
    SCOPE_UNSPECIFIED = 'SCOPE_UNSPECIFIED'
    SCOPE_ZONAL = 'SCOPE_ZONAL'
    SCOPE_REGIONAL = 'SCOPE_REGIONAL'


class PredefinedMachineType(BaseModel):
    machineType: Optional[str] = Field(
        None,
        description='The [machine type](https://cloud.google.com/compute/docs/machine-types). For example: "n1-standard1".',
    )


class DestinationContinent1(Enum):
    DESTINATION_CONTINENT_UNSPECIFIED = 'DESTINATION_CONTINENT_UNSPECIFIED'
    DESTINATION_CONTINENT_ASIA_PACIFIC = 'DESTINATION_CONTINENT_ASIA_PACIFIC'
    DESTINATION_CONTINENT_AFRICA = 'DESTINATION_CONTINENT_AFRICA'
    DESTINATION_CONTINENT_NORTH_AMERICA = 'DESTINATION_CONTINENT_NORTH_AMERICA'
    DESTINATION_CONTINENT_AUTRALIA = 'DESTINATION_CONTINENT_AUTRALIA'
    DESTINATION_CONTINENT_CENTRAL_AMERICA = 'DESTINATION_CONTINENT_CENTRAL_AMERICA'
    DESTINATION_CONTINENT_CHINA = 'DESTINATION_CONTINENT_CHINA'
    DESTINATION_CONTINENT_EASTERN_EUROPE = 'DESTINATION_CONTINENT_EASTERN_EUROPE'
    DESTINATION_CONTINENT_WESTERN_EUROPE = 'DESTINATION_CONTINENT_WESTERN_EUROPE'
    DESTINATION_CONTINENT_EMEA = 'DESTINATION_CONTINENT_EMEA'
    DESTINATION_CONTINENT_INDIA = 'DESTINATION_CONTINENT_INDIA'
    DESTINATION_CONTINENT_MIDDLE_EAST = 'DESTINATION_CONTINENT_MIDDLE_EAST'
    DESTINATION_CONTINENT_SOUTH_AMERICA = 'DESTINATION_CONTINENT_SOUTH_AMERICA'


class RateTier(BaseModel):
    price: Optional[Money] = Field(None, description='The price for this tier.')
    startAmount: Optional[float] = Field(
        None,
        description='The magnitude of usage in which the tier interval begins. Example: "From 100 GiBi the price is $1 per byte" implies `start_amount` = 100',
    )


class Regional(BaseModel):
    name: Optional[str] = Field(
        None,
        description='The [location name](https://cloud.google.com/storage/docs/locations#available-locations). For example: "us-central1" for region.',
    )


class ScenarioConfig(BaseModel):
    estimateDuration: Optional[str] = Field(
        None,
        description='Time frame for the estimate. Workloads must specify usage for this duration. Duration must be at least 1 hour (3,600 seconds) and at most 10 years (315,360,000 seconds). The calculations for years and months are based on a 730-hour (2,628,000-second) month. For durations longer than one month (2,628,000 seconds), the duration is rounded up to the next month, so the estimate shows you the costs for full months. For example, a duration of 3,232,800 seconds (roughly 5 weeks) is rounded up to 2 months.',
    )


class UsageRateTimelineEntry(BaseModel):
    effectiveTime: Optional[EstimationTimePoint] = Field(
        None,
        description='The effective time for this entry. The usage rate is in effect starting at this time until the effective time of the subsequent entry in the timeline. The last entry defines the usage rate until the end of the `Usage` time frame. Must correspond to an integer number of hours.',
    )
    usageRate: Optional[float] = Field(None, description='The usage rate.')


class Bandwidth(Enum):
    BANDWIDTH_UNSPECIFIED = 'BANDWIDTH_UNSPECIFIED'
    BANDWIDTH_BPS_50M = 'BANDWIDTH_BPS_50M'
    BANDWIDTH_BPS_100M = 'BANDWIDTH_BPS_100M'
    BANDWIDTH_BPS_200M = 'BANDWIDTH_BPS_200M'
    BANDWIDTH_BPS_300M = 'BANDWIDTH_BPS_300M'
    BANDWIDTH_BPS_400M = 'BANDWIDTH_BPS_400M'
    BANDWIDTH_BPS_500M = 'BANDWIDTH_BPS_500M'
    BANDWIDTH_BPS_1G = 'BANDWIDTH_BPS_1G'
    BANDWIDTH_BPS_2G = 'BANDWIDTH_BPS_2G'
    BANDWIDTH_BPS_5G = 'BANDWIDTH_BPS_5G'
    BANDWIDTH_BPS_10G = 'BANDWIDTH_BPS_10G'
    BANDWIDTH_BPS_20G = 'BANDWIDTH_BPS_20G'
    BANDWIDTH_BPS_50G = 'BANDWIDTH_BPS_50G'


class Plan(Enum):
    COMMITMENT_PLAN_UNSPECIFIED = 'COMMITMENT_PLAN_UNSPECIFIED'
    TWELVE_MONTH = 'TWELVE_MONTH'
    THIRTY_SIX_MONTH = 'THIRTY_SIX_MONTH'


class VmResourceBasedCud(BaseModel):
    guestAccelerator: Optional[GuestAccelerator] = Field(
        None, description='Guest accelerator, known as GPU.'
    )
    machineSeries: Optional[str] = Field(
        None,
        description='The machine series for CUD. For example: "n1" for general purpose N1 machine type commitments. "n2" for general purpose N2 machine type commitments. "e2" for general purpose E2 machine type commitments. "n2d" for general purpose N2D machine type commitments. "t2d" for general purpose T2D machine type commitments. "c2"/"c2d" for compute-optimized commitments. "m1"/"m2" for the memory-optimized commitments. "a2\' for the accelerator-optimized commitments.',
    )
    memorySizeGb: Optional[float] = Field(
        None,
        description='Memory size of the VM in GB (2^30 bytes). Must be an increment of 0.25 (256 MB).',
    )
    plan: Optional[Plan] = Field(None, description='Commitment usage plan.')
    region: Optional[str] = Field(
        None, description='The region where the VM runs. For example: "us-central1"'
    )
    virtualCpuCount: Optional[str] = Field(
        None,
        description='The number of vCPUs. The number of vCPUs must be an integer of 0 or more and can be even or odd.',
    )


class FieldXgafv(Enum):
    field_1 = '1'
    field_2 = '2'


class Alt(Enum):
    json = 'json'
    media = 'media'
    proto = 'proto'


class Commitment(BaseModel):
    name: Optional[str] = Field(
        None,
        description='Required. A name for this commitment. All commitments in a CostScenario must have unique names. Each name may be at most 128 characters long.',
    )
    vmResourceBasedCud: Optional[VmResourceBasedCud] = Field(
        None, description='A resource-based committed use discount (CUD).'
    )


class CreditEstimate(BaseModel):
    creditAmount: Optional[Money] = Field(
        None, description='The estimated credit amount.'
    )
    creditDescription: Optional[str] = Field(
        None, description='The credit description.'
    )
    creditType: Optional[str] = Field(None, description='The credit type.')


class MachineType(BaseModel):
    customMachineType: Optional[CustomMachineType] = None
    predefinedMachineType: Optional[PredefinedMachineType] = None


class Rate(BaseModel):
    tiers: Optional[List[RateTier]] = Field(None, description='The service tiers.')
    unit: Optional[str] = Field(
        None,
        description="The SKU's pricing unit. For example, if the tier price is $1 per 1000000 Bytes, then this field will show 'By'. The `start_amount` field in each tier will be in this unit.",
    )
    unitCount: Optional[float] = Field(
        None,
        description="The SKU's count for the pricing unit. For example, if the tier price is $1 per 1000000 Bytes, then this column will show 1000000.",
    )


class UsageRateTimeline(BaseModel):
    unit: Optional[str] = Field(
        None,
        description='The unit for the usage rate in each timeline entry. If you provide an incorrect unit for an instance, the correct unit is provided in the error message. The supported units are a subset of [The Unified Code for Units of Measure](https://ucum.org/ucum.html) standard: * **Time units (TIME-UNIT)** * `s` second * `min` minute * `h` hour * `d` day * `wk` week * `mo` month * `yr` year * `ms` millisecond * `us` microsecond * `ns` nanosecond * **Basic storage units (BASIC-STORAGE-UNIT)** * `bit` bit * `By` byte * **Count units (COUNT-UNIT)** * `count` count * **Prefixes (PREFIX)** * `k` kilo (10^3) * `M` mega (10^6) * `G` giga (10^9) * `T` tera (10^12) * `P` peta (10^15) * `Ki` kibi (2^10) * `Mi` mebi (2^20) * `Gi` gibi (2^30) * `Ti` tebi (2^40) * `Pi` pebi (2^50) **Grammar** The grammar also includes these connectors: * `/` division or ratio (as an infix operator). For example: `kBy/{email}` or `MiBy/10ms`. * `.` multiplication or composition (as an infix operator). For example: `GBy.d` or `k{watt}.h`. The grammar for a unit is as follows: ``` Expression = Component { "." Component } { "/" Component } ; Component = ( [ PREFIX ] UNIT | "%" ) [ Annotation ] | Annotation | "1" ; UNIT = TIME-UNIT | STORAGE-UNIT | DATA-UNIT | COUNT-UNIT Annotation = "{" NAME "}" ; ``` Examples: * Request per second: `1/s` or `{requests}/s` * GibiBytes: `GiBy` * GibiBytes * seconds: `GiBy.s`',
    )
    usageRateTimelineEntries: Optional[List[UsageRateTimelineEntry]] = Field(
        None,
        description='The timeline entries. Each entry has a start time and usage rate. The start time specifies the effective time of the usage rate. The entries must be sorted by start time in an increasing order.',
    )


class CostEstimate(BaseModel):
    creditEstimates: Optional[List[CreditEstimate]] = Field(
        None, description='The estimated credits applied.'
    )
    netCostEstimate: Optional[Money] = Field(
        None, description='The estimated net cost after applying credits.'
    )
    preCreditCostEstimate: Optional[Money] = Field(
        None, description='The estimated cost prior to applying credits.'
    )


class Price(BaseModel):
    effectiveTime: Optional[EstimationTimePoint] = Field(
        None,
        description='The timestamp within the estimation time frame when the price was set.',
    )
    priceType: Optional[str] = Field(
        None, description='The type of price. Possible values: "RATE"'
    )
    rate: Optional[Rate] = Field(None, description='A set of tiered rates.')


class Sku(BaseModel):
    displayName: Optional[str] = Field(
        None,
        description='The display name for the SKU. Example: A2 Instance Core running in Americas',
    )
    prices: Optional[List[Price]] = Field(
        None,
        description='A timeline of prices for a SKU in chronological order. Note: The API currently only supports using a constant price for the entire estimation time frame so this list will contain a single value.',
    )
    sku: Optional[str] = Field(
        None,
        description='The resource name for the SKU. Example: "services/DA34-426B-A397/skus/AA95-CD31-42FE"',
    )


class SkuCostEstimate(BaseModel):
    costEstimate: Optional[CostEstimate] = Field(
        None, description='The estimated cost for the usage on this SKU.'
    )
    sku: Optional[str] = Field(
        None,
        description='The resource name for the SKU. Example: "services/DA34-426B-A397/skus/AA95-CD31-42FE" More information about the SKU can be found in the `skus` field of the `CostEstimationResult`.',
    )
    usageAmount: Optional[float] = Field(
        None, description='The amount of usage on this SKU.'
    )
    usageUnit: Optional[str] = Field(
        None, description='The unit for the usage on this SKU.'
    )


class Usage(BaseModel):
    usageRateTimeline: Optional[UsageRateTimeline] = Field(
        None, description='A timeline of usage rates over the estimate interval.'
    )


class VlanAttachment(BaseModel):
    bandwidth: Optional[Bandwidth] = Field(
        None,
        description='Capacities in the [pricing table](https://cloud.google.com/vpc/network-pricing#interconnect-pricing) Examples of capacity are: 50/100/200/300/400/500-Mbps, 1/2/5/10/20/50-Gbps.',
    )
    vlanCount: Optional[Usage] = Field(
        None,
        description='VLAN usage. This is specified as a unitless quantity which indicates the number of VLAN attachment used in interconnect.',
    )


class WorkloadCostEstimate(BaseModel):
    name: Optional[str] = Field(
        None,
        description='The name of the workload, as specified in the `CostScenario`.',
    )
    skuCostEstimates: Optional[List[SkuCostEstimate]] = Field(
        None, description='Estimated costs for each SKU in the workload.'
    )
    workloadTotalCostEstimate: Optional[CostEstimate] = Field(
        None, description='Total estimated costs for the workload.'
    )


class CloudCdnEgressWorkload(BaseModel):
    cacheEgressDestination: Optional[CacheEgressDestination] = Field(
        None, description='The destination for the cache egress charges.'
    )
    cacheEgressRate: Optional[Usage] = Field(
        None,
        description='Cache egress usage. The rate of data cache egressed in the destination. For example : units such as "GiBy/s" or "TBy/mo".',
    )


class CloudCdnWorkload(BaseModel):
    cacheFillOriginService: Optional[CacheFillOriginService] = Field(
        None, description='The source service for the cache fill.'
    )
    cacheFillRate: Optional[Usage] = Field(
        None,
        description='Cache fill usage. The rate of data transferred between cache fill regions. For example: units such as "GiBy/s" or "TBy/mo".',
    )
    cacheFillRegions: Optional[CacheFillRegions] = Field(
        None,
        description='The regions where data is transferred from Google data locations into Google global cache servers. The SKU prices for cache fill across services are the same.',
    )
    cacheLookUpRate: Optional[Usage] = Field(
        None,
        description='Cache look up requests. This is specified to indicate the number of requests. For example: units such as "1/s".',
    )


class CloudInterconnectEgressWorkload(BaseModel):
    egressRate: Optional[Usage] = Field(
        None,
        description='Data egress usage. This usage applies when you move or copy data from one Google Cloud service to another service. Expected units such as "GiBy/s, By/s, etc."',
    )
    interconnectConnectionLocation: Optional[InterconnectConnectionLocation] = Field(
        None,
        description='Locations in the [Interconnect connection location table](https://cloud.google.com/vpc/network-pricing#interconnect-pricing). This is the interconnect egress charges.',
    )


class CloudInterconnectWorkload(BaseModel):
    interconnectAttachments: Optional[List[VlanAttachment]] = Field(
        None, description='VLAN attachment used for interconnect.'
    )
    interconnectType: Optional[InterconnectType] = Field(
        None, description='Vlan attachment type.'
    )
    linkType: Optional[LinkType] = Field(
        None, description='Interconnect circuit link type.'
    )
    provisionedLinkCount: Optional[Usage] = Field(
        None,
        description='Interconnect usage. This is specified as a unitless quantity which indicates the number of circuit provisioned in interconnect.',
    )


class CloudStorageEgressWorkload(BaseModel):
    destinationContinent: Optional[DestinationContinent] = Field(
        None, description='Where the data is sent to.'
    )
    egressRate: Optional[Usage] = Field(
        None,
        description='Egress usage rate. This usage applies when you move or copy data from one Cloud Storage bucket to another or when another Google Cloud service accesses data in your Cloud Storage bucket. Expected units such as "GiBy/s, By/s, ..."',
    )
    sourceContinent: Optional[SourceContinent] = Field(
        None, description='Where the data comes from.'
    )


class CloudStorageWorkload(BaseModel):
    dataRetrieval: Optional[Usage] = Field(
        None,
        description='Data retrieval usage. A retrieval cost applies when data or metadata is read, copied, or rewritten . For example: units such as "GiBy/s" or "By/s".',
    )
    dataStored: Optional[Usage] = Field(
        None,
        description='Data storage usage. The amount of data stored in buckets. For example: units such as "GiBy/s" or "TBy/mo".',
    )
    dualRegion: Optional[DualRegional] = Field(
        None, description='Specify dual regions.'
    )
    multiRegion: Optional[MultiRegional] = Field(
        None, description='Specify multi regions.'
    )
    operationA: Optional[Usage] = Field(
        None,
        description='Class A operation usage in Cloud Storage, such as listing the objects in buckets. See the [operations pricing](https://cloud.google.com/storage/pricing#operations-pricing) tables for a list of which operations fall into each class. For example: units such as "1/s".',
    )
    operationB: Optional[Usage] = Field(
        None,
        description='Class B operation usage in Cloud Storage, such as `getIamPolicy`. See the [operations pricing](https://cloud.google.com/storage/pricing#operations-pricing) tables for a list of which operations fall into each class. For example: units such as "1/s".',
    )
    region: Optional[Regional] = Field(None, description='Specify a single region.')
    storageClass: Optional[str] = Field(
        None,
        description='The [storage class](https://cloud.google.com/storage/docs/storage-classes#classes) of the data and operation. For example: "standard" and "nearline".',
    )


class CommitmentCostEstimate(BaseModel):
    commitmentTotalCostEstimate: Optional[CostEstimate] = Field(
        None, description='Total estimated costs for the commitment.'
    )
    name: Optional[str] = Field(
        None,
        description='The name of the commitment, as specified in the `CostScenario`.',
    )
    skuCostEstimates: Optional[List[SkuCostEstimate]] = Field(
        None, description='Estimated costs for each SKU in the commitment.'
    )


class InterRegionEgress(BaseModel):
    destinationRegion: Optional[str] = Field(
        None,
        description='Which [region](https://cloud.google.com/compute/docs/regions-zones) the egress data goes to.',
    )
    egressRate: Optional[Usage] = Field(
        None,
        description='VM to VM egress usage. Expected units such as "GiBy/s, By/s, etc."',
    )
    sourceRegion: Optional[str] = Field(
        None,
        description='Which [region](https://cloud.google.com/compute/docs/regions-zones) the egress data comes from.',
    )


class IntraRegionEgress(BaseModel):
    egressRate: Optional[Usage] = Field(
        None,
        description='VM to VM egress usage. Expected units such as "GiBy/s, By/s, etc."',
    )


class PersistentDisk(BaseModel):
    diskSize: Optional[Usage] = Field(
        None, description='Specifies the size of disk. Must be at least 10 GB.'
    )
    diskType: Optional[str] = Field(
        None,
        description='The [disk type](https://cloud.google.com/compute/docs/disks#disk-types). For example: "pd-standard".',
    )
    provisionedIops: Optional[Usage] = Field(
        None,
        description='Indicates how many IOPS to provision for the disk for extreme persistent disks. This sets the number of I/O operations per second that the disk can handle. Values must be between 10,000 and 120,000.',
    )
    scope: Optional[Scope] = Field(
        None,
        description='The geographic scope of the disk. Defaults to `SCOPE_ZONAL` if not specified.',
    )


class PremiumTierEgressWorkload(BaseModel):
    destinationContinent: Optional[DestinationContinent1] = Field(
        None, description='Where the data is sent to.'
    )
    egressRate: Optional[Usage] = Field(
        None,
        description='Premium Tier egress usage. Expected units such as "GiBy/s, By/s, etc."',
    )
    sourceRegion: Optional[str] = Field(
        None,
        description='Which [region](https://cloud.google.com/compute/docs/regions-zones) the egress data comes from.',
    )


class SegmentCostEstimate(BaseModel):
    commitmentCostEstimates: Optional[List[CommitmentCostEstimate]] = Field(
        None, description='Estimated costs for each commitment.'
    )
    segmentStartTime: Optional[EstimationTimePoint] = Field(
        None, description='Timestamp for the start of the segment.'
    )
    segmentTotalCostEstimate: Optional[CostEstimate] = Field(
        None, description='Total estimated costs for the time segment.'
    )
    workloadCostEstimates: Optional[List[WorkloadCostEstimate]] = Field(
        None, description='Estimated costs for each workload.'
    )


class StandardTierEgressWorkload(BaseModel):
    egressRate: Optional[Usage] = Field(
        None,
        description='Standard tier egress usage. Expected units such as "GiBy/s, By/s, etc."',
    )
    sourceRegion: Optional[str] = Field(
        None,
        description='Which [region](https://cloud.google.com/compute/docs/regions-zones) the egress data comes from.',
    )


class VmToVmEgressWorkload(BaseModel):
    interRegionEgress: Optional[InterRegionEgress] = None
    intraRegionEgress: Optional[IntraRegionEgress] = None


class ComputeVmWorkload(BaseModel):
    enableConfidentialCompute: Optional[bool] = Field(
        None,
        description='Defines whether each instance has confidential compute enabled.',
    )
    guestAccelerator: Optional[GuestAccelerator] = Field(
        None, description='Guest accelerators attached to each machine.'
    )
    instancesRunning: Optional[Usage] = Field(
        None,
        description='VM usage. This is specified as a unitless quantity which indicates the number of instances running.',
    )
    licenses: Optional[List[str]] = Field(
        None, description='Premium image licenses used by each instance.'
    )
    machineType: Optional[MachineType] = Field(None, description='The machine type.')
    persistentDisks: Optional[List[PersistentDisk]] = Field(
        None,
        description='Persistent disks attached to each instance. Must include a boot disk.',
    )
    preemptible: Optional[bool] = Field(
        None, description='Defines whether each instance is preemptible.'
    )
    region: Optional[str] = Field(
        None,
        description='The [region](https://cloud.google.com/compute/docs/regions-zones) where the VMs run. For example: "us-central1".',
    )


class CostEstimationResult(BaseModel):
    currencyCode: Optional[str] = Field(
        None, description='Required. The ISO 4217 currency code for the cost estimate.'
    )
    segmentCostEstimates: Optional[List[SegmentCostEstimate]] = Field(
        None,
        description='Required. Estimated costs for each idealized month of a `CostScenario`.',
    )
    skus: Optional[List[Sku]] = Field(
        None, description='Required. Information about SKUs used in the estimate.'
    )


class EstimateCostScenarioForBillingAccountResponse(BaseModel):
    costEstimationResult: Optional[CostEstimationResult] = Field(
        None, description='The result of the cost estimation.'
    )


class EstimateCostScenarioWithListPriceResponse(BaseModel):
    costEstimationResult: Optional[CostEstimationResult] = Field(
        None, description='The result of the cost estimation.'
    )


class Workload(BaseModel):
    cloudCdnEgressWorkload: Optional[CloudCdnEgressWorkload] = Field(
        None, description='Usage on Google Cloud CDN Egress.'
    )
    cloudCdnWorkload: Optional[CloudCdnWorkload] = Field(
        None, description='Usage on Google Cloud CDN.'
    )
    cloudInterconnectEgressWorkload: Optional[CloudInterconnectEgressWorkload] = Field(
        None, description='Usage on Google Cloud Interconnect Egress.'
    )
    cloudInterconnectWorkload: Optional[CloudInterconnectWorkload] = Field(
        None, description='Usage on Google Cloud Interconnect.'
    )
    cloudStorageEgressWorkload: Optional[CloudStorageEgressWorkload] = Field(
        None, description='Usage on a cloud storage egress.'
    )
    cloudStorageWorkload: Optional[CloudStorageWorkload] = Field(
        None, description='Usage on Google Cloud Storage.'
    )
    computeVmWorkload: Optional[ComputeVmWorkload] = Field(
        None, description='Usage of a Google Compute Engine Virtual Machine.'
    )
    name: Optional[str] = Field(
        None,
        description='Required. A name for this workload. All workloads in a `CostScenario` must have a unique `name`. Each `name` may be at most 128 characters long.',
    )
    premiumTierEgressWorkload: Optional[PremiumTierEgressWorkload] = Field(
        None, description='Usage on Premium Tier Internet Egress.'
    )
    standardTierEgressWorkload: Optional[StandardTierEgressWorkload] = Field(
        None, description='Usage on Standard Tier Internet Egress.'
    )
    vmToVmEgressWorkload: Optional[VmToVmEgressWorkload] = Field(
        None, description='Usage on Vm to Vm Egress.'
    )


class CostScenario(BaseModel):
    commitments: Optional[List[Commitment]] = Field(
        None,
        description='New commitments to estimate the costs for. The cost of the commitments will be included in the estimate result and discounts the commitment entitles will be included in the workload cost estimates. A maximum of 100 workloads can be provided.',
    )
    scenarioConfig: Optional[ScenarioConfig] = Field(
        None, description='Configuration for the scenario.'
    )
    workloads: Optional[List[Workload]] = Field(
        None,
        description='The Google Cloud usage whose costs are estimated. A maximum of 100 workloads can be provided.',
    )


class EstimateCostScenarioForBillingAccountRequest(BaseModel):
    costScenario: Optional[CostScenario] = Field(
        None, description='The scenario to estimate costs for.'
    )


class EstimateCostScenarioWithListPriceRequest(BaseModel):
    costScenario: Optional[CostScenario] = Field(
        None, description='The scenario to estimate costs for.'
    )
